OPENAI='openai'
GPT_4='GPT_4'
GPT_4O='GPT_4O'
GPT_4O_TEXT='GPT_4O_TEXT'
GPT_4O_IMAGE='GPT_4O_IMAGE'
GEMINI='GEMINI'
GEMINI_PRO_VISION= 'GEMINI_PRO_VISION'
INTERNAL='INTERNAL'
MIXTRAL='MIXTRAL'
PROMPT_TEMPLATE='Prompt_Template'

#constants for bert
MODEL_PATH='../models/Models'
TOKENIZER_PATH='../models/Tokenizer'