apiVersion: apps/v1
kind: Deployment
metadata:
  name: fairness-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: responsible-ai-fairness
  template:
    metadata:
      labels:
        app: responsible-ai-fairness
    spec:
      containers:
        - name: responsible-ai-fairness
          image: ${{ secrets.DOCKER_USERNAME }}/responsible-ai-fairness:latest
          ports:
            - containerPort: 8102
---
apiVersion: v1
kind: Service
metadata:
  name: fairness-service
spec:
  selector:
    app: responsible-ai-fairness
  ports:
    - protocol: TCP
      port: 8102
      targetPort: 8102
