apiVersion: apps/v1
kind: Deployment
metadata:
  name: security-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: responsible-ai-security
  template:
    metadata:
      labels:
        app: responsible-ai-security
    spec:
      containers:
        - name: responsible-ai-security
          image: ${{ secrets.DOCKER_USERNAME }}/responsible-ai-security:latest
          ports:
            - containerPort: 8700
---
apiVersion: v1
kind: Service
metadata:
  name: security-service
spec:
  selector:
    app: responsible-ai-security
  ports:
    - protocol: TCP
      port: 8700
      targetPort: 8700
