"""
fileName: local_constants.py
description: Local constants for usecase  module
"""

DELTED_SUCCESS_MESSAGE="Successfully deleted the usecase :"
USECASE_ALREADY_EXISTS= "Usecase with name PLACEHOLDER_TEXT already exists"
USECASE_NOT_FOUND_ERROR="Usecase id PLACEHOLDER_TEXT Not Found"
USECASE_NAME_VALIDATION_ERROR="Usecase name should not be empty"
SPACE_DELIMITER=" "
PLACEHOLDER_TEXT="PLACEHOLDER_TEXT"
HTTP_STATUS_BAD_REQUEST=500
HTTP_STATUS_NOT_FOUND=404
HTTP_STATUS_409_CODE=409
HTTP_422_UNPROCESSABLE_ENTITY="422"
HTTP_415_UNSUPPORTED_MEDIA_TYPE=415
UNSUPPPORTED_MEDIA_TYPE_ERROR="Unsupported media type: "